### ISSUE TITLE
Error creating SSL certificate transip

### ISSUE THREAD

**Issue by rubenelshof** [zjean/caddy-docker#2]
Hi,

Before I get started I apologize for using this repo's issues with a issue for a different repo but I cant create a issue at the plugin repo.
I want to use your caddy plugin for transip.
Unfortunately I am getting a error and panic on creating a certificate & I was hoping you could help me with this.
Thank you in advance.

Below the error.
```
{"level":"info","ts":1697821251.426163,"logger":"tls.issuance.acme","msg":"waiting on internal rate limiter","identifiers":["example.nl"],"ca":"https://acme-v02.api.letsencrypt.org/directory","account":""}
{"level":"info","ts":1697821251.4261837,"logger":"tls.issuance.acme","msg":"done waiting on internal rate limiter","identifiers":["example.nl"],"ca":"https://acme-v02.api.letsencrypt.org/directory","account":""}
{"level":"info","ts":1697821252.0967462,"logger":"tls.issuance.acme.acme_client","msg":"trying to solve challenge","identifier":"example.nl","challenge_type":"dns-01","ca":"https://acme-v02.api.letsencrypt.org/directory"}
{"level":"error","ts":1697821252.0968955,"logger":"tls.issuance.acme.acme_client","msg":"cleaning up solver","identifier":"example.nl","challenge_type":"dns-01","error":"no memory of presenting a DNS record for \"_acme-challenge.example.nl\" (usually OK if presenting also failed)"}
{"level":"info","ts":1697821252.096912,"logger":"tls.obtain","msg":"releasing lock","identifier":"example.nl"}
{"level":"info","ts":1697821252.0970838,"msg":"panic: certificate worker: runtime error: invalid memory address or nil pointer dereference\ngoroutine 1106 [running]:\ngithub.com/caddyserver/certmagic.(*jobManager).worker.func1()\n\tgithub.com/caddyserver/certmagic@v0.19.2/async.go:58 +0x65\npanic({0x1776500?, 0x2b1d1f0?})\n\truntime/panic.go:914 +0x21f\ngithub.com/transip/gotransip/v6/domain.(*Repository).AddDNSEntry(0x0, {0xc0002e2a60, 0xe}, {{0xc0003e37e0, 0xf}, 0x12c, {0x19ccb41, 0x3}, {0xc0007e4570, 0x2b}})\n\tgithub.com/transip/gotransip/v6@v6.6.1/domain/repository.go:144 +0x184\ngithub.com/zjean/libdns-transip.(*Provider).addDNSEntry(0xc00056a2a0, {0x100?, 0xc0?}, {0xc0002e2a60, 0xe}, {{0x0, 0x0}, {0x19ccb41, 0x3}, {0xc0003e37e0, ...}, ...})\n\tgithub.com/zjean/libdns-transip@v0.1.3/client.go:67 +0x217\ngithub.com/zjean/libdns-transip.(*Provider).AppendRecords(0xc000066800?, {0x1eaf3f0, 0xc000867470}, {0xc0002e2a60, 0xf}, {0xc0006c9590?, 0x1, 0x1?})\n\tgithub.com/zjean/libdns-transip@v0.1.3/provider.go:46 +0x27e\ngithub.com/caddyserver/certmagic.(*DNS01Solver).Present(0xc00090e4e0, {0x1eaf3f0, 0xc000867470}, {{0xc000557dc0, 0x6}, {0xc000898af0, 0x46}, {0xc000557dc6, 0x7}, {0x0, ...}, ...})\n\tgithub.com/caddyserver/certmagic@v0.19.2/solvers.go:312 +0x478\ngithub.com/caddyserver/certmagic.solverWrapper.Present({{0x1ea65e0?, 0xc00090e4e0?}}, {0x1eaf3f0, 0xc000867470}, {{0xc000557dc0, 0x6}, {0xc000898af0, 0x46}, {0xc000557dc6, 0x7}, ...})\n\tgithub.com/caddyserver/certmagic@v0.19.2/solvers.go:724 +0x22e\ngithub.com/mholt/acmez.(*Client).presentForNextChallenge(0xc0009087e0, {0x1eaf3f0, 0xc000867470}, 0xc00004b6c0)\n\tgithub.com/mholt/acmez@v1.2.0/client.go:482 +0x7ab\ngithub.com/mholt/acmez.(*Client).solveChallenges(_, {_, _}, {{0xc000557858, 0x5}, {0x0, 0x0, 0x0}, 0x1, {0x0, ...}, ...}, ...)\n\tgithub.com/mholt/acmez@v1.2.0/client.go:433 +0x276\ngithub.com/mholt/acmez.(*Client).ObtainCertificateUsingCSRSource(0xc0009087e0, {0x1eaf3f0, 0xc000867470}, {{0xc000557858, 0x5}, {0x0, 0x0, 0x0}, 0x1, {0x0, ...}, ...}, ...)\n\tgithub.com/mholt/acmez@v1.2.0/client.go:119 +0x3f8\ngithub.com/mholt/acmez.(*Client).ObtainCertificateUsingCSR(0x0?, {0x1eaf3f0, 0xc000867470}, {{0xc000557858, 0x5}, {0x0, 0x0, 0x0}, 0x1, {0x0, ...}, ...}, ...)\n\tgithub.com/mholt/acmez@v1.2.0/client.go:270 +0x132\ngithub.com/caddyserver/certmagic.(*ACMEIssuer).doIssue(0xc000867470?, {0x1eaf3f0, 0xc000867470}, 0x0?, 0x0)\n\tgithub.com/caddyserver/certmagic@v0.19.2/acmeissuer.go:396 +0x19c\ngithub.com/caddyserver/certmagic.(*ACMEIssuer).Issue(0xc000848c80, {0x1eaf3f0, 0xc000867470}, 0xc0000f3501?)\n\tgithub.com/caddyserver/certmagic@v0.19.2/acmeissuer.go:325 +0xa5\ngithub.com/caddyserver/caddy/v2/modules/caddytls.(*ACMEIssuer).Issue(0x19f2d45?, {0x1eaf3f0?, 0xc000867470?}, 0xc000908700?)\n\tgithub.com/caddyserver/caddy/v2@v2.7.5/modules/caddytls/acmeissuer.go:234 +0x25\ngithub.com/caddyserver/certmagic.(*Config).obtainCert.func2({0x1eaf3f0, 0xc000867470})\n\tgithub.com/caddyserver/certmagic@v0.19.2/config.go:586 +0xbc4\ngithub.com/caddyserver/certmagic.doWithRetry({0x1eaf428, 0xc0000a8870}, 0x1eb7518?, 0xc0006e7a98)\n\tgithub.com/caddyserver/certmagic@v0.19.2/async.go:104 +0x218\ngithub.com/caddyserver/certmagic.(*Config).obtainCert(0xc0003596c0, {0x1eaf428, 0xc0000a8870}, {0xc00056f2a0, 0xe}, 0x0)\n\tgithub.com/caddyserver/certmagic@v0.19.2/config.go:650 +0x717\ngithub.com/caddyserver/certmagic.(*Config).ObtainCertAsync(...)\n\tgithub.com/caddyserver/certmagic@v0.19.2/config.go:479\ngithub.com/caddyserver/certmagic.(*Config).manageOne.func1()\n\tgithub.com/caddyserver/certmagic@v0.19.2/config.go:398 +0x73\ngithub.com/caddyserver/certmagic.(*jobManager).worker(0x2b2e4c0)\n\tgithub.com/caddyserver/certmagic@v0.19.2/async.go:73 +0x10f\ncreated by github.com/caddyserver/certmagic.(*jobManager).Submit in goroutine 1069\n\tgithub.com/caddyserver/certmagic@v0.19.2/async.go:50 +0x279"}
```

My Caddy config:
```
example.nl {
        tls {
                dns transip {env.TRANSIP_USERNAME, env.TRANSIP_PRIVATE_KEY}
        }
        root * /var/www/example.nl
        file_server
}
```

env file:
```
TRANSIP_USERNAME=username
TRANSIP_PRIVATE_KEY=/config/caddy/config/transip_api.key
```

**Comment by zjean** [comment]
Hey @rubenelshof 
No problem. Do you use the docker image of this repository? (zjean/caddy-docker), or do you build the image yourself?

I have a different configuration for my tls block:
```
tls {
		dns transip [my-account-name] /transip/transip.key
	}
```

Does that make a difference?

I have mounted my transip.key file into the container.

**Comment by rubenelshof** [comment]
> Hey @rubenelshof No problem. Do you use the docker image of this repository? (zjean/caddy-docker), or do you build the image yourself?
> 
> I have a different configuration for my tls block:
> 
> ```
> tls {
> 		dns transip [my-account-name] /transip/transip.key
> 	}
> ```
> 
> Does that make a difference?
> 
> I have mounted my transip.key file into the container.

I build my own image.
Your TLS block has solved the first issue but I now have 2 new issues.

For some reason the TRANSIP_PRIVATE_KEY env variable still gives the panic but directly putting the file location in Caddyfile solves this issue.
```
dns transip [{env.TRANSIP_USERNAME}] {env.TRANSIP_PRIVATE_KEY}      # This fails
dns transip [{env.TRANSIP_USERNAME}] /config/caddy/config/transip_api.key      This works.
```

With the working config I now have the following issue.
```
Obtain: [example.nl.nl] solving challenges: presenting for challenge: adding temporary record for zone \"example.nl.nl.\": could not get token from authenticator: error requesting token: Your key signature is invalid or API is not enabled in your account
```
I have checked that I have the API enabled. I also created a new Key pair just to be sure.

**Comment by rubenelshof** [comment]
Solved!

I removed the brackets around the username in the TLS block.
```
# This fails
tls {
           dns transip [my-account-name] /transip/transip.key
}

# This works
tls {
           dns transip my-account-name /transip/transip.key
}
```

Has nothing to do with time in between.

**Comment by zjean** [comment]
Glad you figured it out!
